### ISSUE TITLE
From environmental variables to yaml-file

### ISSUE THREAD

**Issue by hurricane642** [perturbo-code/perturbopy#13]
Hey,
In the current version, we use environmental variables for `PERTURBO_SCRATCH` folder and `PERTURBO_RUN` command. It's not really convenient, because user need to define this command every launch of session. Probably, it's better to make yaml-file with the following structure (for example):
```
prel_coms:
    - module load perturbo
    - module load qe
comp_info:
    perturbo: srun -n 8 perturbo.x -npools 8
    scratch: tmp/
```
And run this commands already inside the tests.

Also, we can  make unified YAML-file (Probably, I'll use similar structure for the testing `qe2pert`)
